# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "D:\Clion\CLion 202.5428.21\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "D:\Clion\CLion 202.5428.21\bin\cmake\win\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Clion\Projects\udemy_course

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Clion\Projects\udemy_course

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	echo >nul && "D:\Clion\CLion 202.5428.21\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache

.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "D:\Clion\CLion 202.5428.21\bin\cmake\win\bin\cmake.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache

.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Clion\Projects\udemy_course\CMakeFiles D:\Clion\Projects\udemy_course\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Clion\Projects\udemy_course\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean

.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named udemy_course

# Build rule for target.
udemy_course: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) udemy_course
.PHONY : udemy_course

# fast build rule for target.
udemy_course\fast:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\build
.PHONY : udemy_course\fast

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\main.cpp.s
.PHONY : main.cpp.s

section_inheritance\inheritance.obj: section_inheritance\inheritance.cpp.obj

.PHONY : section_inheritance\inheritance.obj

# target to build an object file
section_inheritance\inheritance.cpp.obj:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_inheritance\inheritance.cpp.obj
.PHONY : section_inheritance\inheritance.cpp.obj

section_inheritance\inheritance.i: section_inheritance\inheritance.cpp.i

.PHONY : section_inheritance\inheritance.i

# target to preprocess a source file
section_inheritance\inheritance.cpp.i:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_inheritance\inheritance.cpp.i
.PHONY : section_inheritance\inheritance.cpp.i

section_inheritance\inheritance.s: section_inheritance\inheritance.cpp.s

.PHONY : section_inheritance\inheritance.s

# target to generate assembly for a file
section_inheritance\inheritance.cpp.s:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_inheritance\inheritance.cpp.s
.PHONY : section_inheritance\inheritance.cpp.s

section_iostream\streams.obj: section_iostream\streams.cpp.obj

.PHONY : section_iostream\streams.obj

# target to build an object file
section_iostream\streams.cpp.obj:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_iostream\streams.cpp.obj
.PHONY : section_iostream\streams.cpp.obj

section_iostream\streams.i: section_iostream\streams.cpp.i

.PHONY : section_iostream\streams.i

# target to preprocess a source file
section_iostream\streams.cpp.i:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_iostream\streams.cpp.i
.PHONY : section_iostream\streams.cpp.i

section_iostream\streams.s: section_iostream\streams.cpp.s

.PHONY : section_iostream\streams.s

# target to generate assembly for a file
section_iostream\streams.cpp.s:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_iostream\streams.cpp.s
.PHONY : section_iostream\streams.cpp.s

section_oop\Account.obj: section_oop\Account.cpp.obj

.PHONY : section_oop\Account.obj

# target to build an object file
section_oop\Account.cpp.obj:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_oop\Account.cpp.obj
.PHONY : section_oop\Account.cpp.obj

section_oop\Account.i: section_oop\Account.cpp.i

.PHONY : section_oop\Account.i

# target to preprocess a source file
section_oop\Account.cpp.i:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_oop\Account.cpp.i
.PHONY : section_oop\Account.cpp.i

section_oop\Account.s: section_oop\Account.cpp.s

.PHONY : section_oop\Account.s

# target to generate assembly for a file
section_oop\Account.cpp.s:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_oop\Account.cpp.s
.PHONY : section_oop\Account.cpp.s

section_oop\class_constructor.obj: section_oop\class_constructor.cpp.obj

.PHONY : section_oop\class_constructor.obj

# target to build an object file
section_oop\class_constructor.cpp.obj:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_oop\class_constructor.cpp.obj
.PHONY : section_oop\class_constructor.cpp.obj

section_oop\class_constructor.i: section_oop\class_constructor.cpp.i

.PHONY : section_oop\class_constructor.i

# target to preprocess a source file
section_oop\class_constructor.cpp.i:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_oop\class_constructor.cpp.i
.PHONY : section_oop\class_constructor.cpp.i

section_oop\class_constructor.s: section_oop\class_constructor.cpp.s

.PHONY : section_oop\class_constructor.s

# target to generate assembly for a file
section_oop\class_constructor.cpp.s:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_oop\class_constructor.cpp.s
.PHONY : section_oop\class_constructor.cpp.s

section_operator_overloading\overloaded_equal.obj: section_operator_overloading\overloaded_equal.cpp.obj

.PHONY : section_operator_overloading\overloaded_equal.obj

# target to build an object file
section_operator_overloading\overloaded_equal.cpp.obj:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_operator_overloading\overloaded_equal.cpp.obj
.PHONY : section_operator_overloading\overloaded_equal.cpp.obj

section_operator_overloading\overloaded_equal.i: section_operator_overloading\overloaded_equal.cpp.i

.PHONY : section_operator_overloading\overloaded_equal.i

# target to preprocess a source file
section_operator_overloading\overloaded_equal.cpp.i:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_operator_overloading\overloaded_equal.cpp.i
.PHONY : section_operator_overloading\overloaded_equal.cpp.i

section_operator_overloading\overloaded_equal.s: section_operator_overloading\overloaded_equal.cpp.s

.PHONY : section_operator_overloading\overloaded_equal.s

# target to generate assembly for a file
section_operator_overloading\overloaded_equal.cpp.s:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_operator_overloading\overloaded_equal.cpp.s
.PHONY : section_operator_overloading\overloaded_equal.cpp.s

section_operator_overloading\overloaded_operators_global.obj: section_operator_overloading\overloaded_operators_global.cpp.obj

.PHONY : section_operator_overloading\overloaded_operators_global.obj

# target to build an object file
section_operator_overloading\overloaded_operators_global.cpp.obj:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_operator_overloading\overloaded_operators_global.cpp.obj
.PHONY : section_operator_overloading\overloaded_operators_global.cpp.obj

section_operator_overloading\overloaded_operators_global.i: section_operator_overloading\overloaded_operators_global.cpp.i

.PHONY : section_operator_overloading\overloaded_operators_global.i

# target to preprocess a source file
section_operator_overloading\overloaded_operators_global.cpp.i:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_operator_overloading\overloaded_operators_global.cpp.i
.PHONY : section_operator_overloading\overloaded_operators_global.cpp.i

section_operator_overloading\overloaded_operators_global.s: section_operator_overloading\overloaded_operators_global.cpp.s

.PHONY : section_operator_overloading\overloaded_operators_global.s

# target to generate assembly for a file
section_operator_overloading\overloaded_operators_global.cpp.s:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_operator_overloading\overloaded_operators_global.cpp.s
.PHONY : section_operator_overloading\overloaded_operators_global.cpp.s

section_operator_overloading\wi_operator_overloading.obj: section_operator_overloading\wi_operator_overloading.cpp.obj

.PHONY : section_operator_overloading\wi_operator_overloading.obj

# target to build an object file
section_operator_overloading\wi_operator_overloading.cpp.obj:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_operator_overloading\wi_operator_overloading.cpp.obj
.PHONY : section_operator_overloading\wi_operator_overloading.cpp.obj

section_operator_overloading\wi_operator_overloading.i: section_operator_overloading\wi_operator_overloading.cpp.i

.PHONY : section_operator_overloading\wi_operator_overloading.i

# target to preprocess a source file
section_operator_overloading\wi_operator_overloading.cpp.i:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_operator_overloading\wi_operator_overloading.cpp.i
.PHONY : section_operator_overloading\wi_operator_overloading.cpp.i

section_operator_overloading\wi_operator_overloading.s: section_operator_overloading\wi_operator_overloading.cpp.s

.PHONY : section_operator_overloading\wi_operator_overloading.s

# target to generate assembly for a file
section_operator_overloading\wi_operator_overloading.cpp.s:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_operator_overloading\wi_operator_overloading.cpp.s
.PHONY : section_operator_overloading\wi_operator_overloading.cpp.s

section_polymorphism\polymorphism.obj: section_polymorphism\polymorphism.cpp.obj

.PHONY : section_polymorphism\polymorphism.obj

# target to build an object file
section_polymorphism\polymorphism.cpp.obj:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_polymorphism\polymorphism.cpp.obj
.PHONY : section_polymorphism\polymorphism.cpp.obj

section_polymorphism\polymorphism.i: section_polymorphism\polymorphism.cpp.i

.PHONY : section_polymorphism\polymorphism.i

# target to preprocess a source file
section_polymorphism\polymorphism.cpp.i:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_polymorphism\polymorphism.cpp.i
.PHONY : section_polymorphism\polymorphism.cpp.i

section_polymorphism\polymorphism.s: section_polymorphism\polymorphism.cpp.s

.PHONY : section_polymorphism\polymorphism.s

# target to generate assembly for a file
section_polymorphism\polymorphism.cpp.s:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_polymorphism\polymorphism.cpp.s
.PHONY : section_polymorphism\polymorphism.cpp.s

section_smart_pointers\shared_pointers.obj: section_smart_pointers\shared_pointers.cpp.obj

.PHONY : section_smart_pointers\shared_pointers.obj

# target to build an object file
section_smart_pointers\shared_pointers.cpp.obj:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_smart_pointers\shared_pointers.cpp.obj
.PHONY : section_smart_pointers\shared_pointers.cpp.obj

section_smart_pointers\shared_pointers.i: section_smart_pointers\shared_pointers.cpp.i

.PHONY : section_smart_pointers\shared_pointers.i

# target to preprocess a source file
section_smart_pointers\shared_pointers.cpp.i:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_smart_pointers\shared_pointers.cpp.i
.PHONY : section_smart_pointers\shared_pointers.cpp.i

section_smart_pointers\shared_pointers.s: section_smart_pointers\shared_pointers.cpp.s

.PHONY : section_smart_pointers\shared_pointers.s

# target to generate assembly for a file
section_smart_pointers\shared_pointers.cpp.s:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_smart_pointers\shared_pointers.cpp.s
.PHONY : section_smart_pointers\shared_pointers.cpp.s

section_smart_pointers\unique_pointers.obj: section_smart_pointers\unique_pointers.cpp.obj

.PHONY : section_smart_pointers\unique_pointers.obj

# target to build an object file
section_smart_pointers\unique_pointers.cpp.obj:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_smart_pointers\unique_pointers.cpp.obj
.PHONY : section_smart_pointers\unique_pointers.cpp.obj

section_smart_pointers\unique_pointers.i: section_smart_pointers\unique_pointers.cpp.i

.PHONY : section_smart_pointers\unique_pointers.i

# target to preprocess a source file
section_smart_pointers\unique_pointers.cpp.i:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_smart_pointers\unique_pointers.cpp.i
.PHONY : section_smart_pointers\unique_pointers.cpp.i

section_smart_pointers\unique_pointers.s: section_smart_pointers\unique_pointers.cpp.s

.PHONY : section_smart_pointers\unique_pointers.s

# target to generate assembly for a file
section_smart_pointers\unique_pointers.cpp.s:
	$(MAKE) -f CMakeFiles\udemy_course.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\udemy_course.dir\section_smart_pointers\unique_pointers.cpp.s
.PHONY : section_smart_pointers\unique_pointers.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... udemy_course
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... section_inheritance/inheritance.obj
	@echo ... section_inheritance/inheritance.i
	@echo ... section_inheritance/inheritance.s
	@echo ... section_iostream/streams.obj
	@echo ... section_iostream/streams.i
	@echo ... section_iostream/streams.s
	@echo ... section_oop/Account.obj
	@echo ... section_oop/Account.i
	@echo ... section_oop/Account.s
	@echo ... section_oop/class_constructor.obj
	@echo ... section_oop/class_constructor.i
	@echo ... section_oop/class_constructor.s
	@echo ... section_operator_overloading/overloaded_equal.obj
	@echo ... section_operator_overloading/overloaded_equal.i
	@echo ... section_operator_overloading/overloaded_equal.s
	@echo ... section_operator_overloading/overloaded_operators_global.obj
	@echo ... section_operator_overloading/overloaded_operators_global.i
	@echo ... section_operator_overloading/overloaded_operators_global.s
	@echo ... section_operator_overloading/wi_operator_overloading.obj
	@echo ... section_operator_overloading/wi_operator_overloading.i
	@echo ... section_operator_overloading/wi_operator_overloading.s
	@echo ... section_polymorphism/polymorphism.obj
	@echo ... section_polymorphism/polymorphism.i
	@echo ... section_polymorphism/polymorphism.s
	@echo ... section_smart_pointers/shared_pointers.obj
	@echo ... section_smart_pointers/shared_pointers.i
	@echo ... section_smart_pointers/shared_pointers.s
	@echo ... section_smart_pointers/unique_pointers.obj
	@echo ... section_smart_pointers/unique_pointers.i
	@echo ... section_smart_pointers/unique_pointers.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

